FROM influxdb:1.8

ENV TZ=America/Chicago
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ENV INFLUXDB_DB="homie"
ENV INFLUXDB_ADMIN_USER="admin"
ENV INFLUXDB_ADMIN_PASSWORD="mypassword"
ENV INFLUXDB_READ_USER="millikan"
ENV INFLUXDB_READ_USER_PASSWORD="1.602e-19"

RUN ./init-influxdb.sh
